# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000
prioritized_buffer: False
prioritized_buffer_alpha: 0.6

# update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

mac: "cent_mac"
agent: "rnn_cent_pet"
standardise_returns: False
standardise_rewards: True

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
#use_rnn: True
use_rnn: True  # For spread-8
mixer: "qmix"
#hidden_dim: 128 # For RWARE
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "qmix_cent_petr"

